version: '3.9'
services:
  web-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
  mysqldb:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=p@ssw0rd1
    volumes:
      - mysql:/var/lib/lib/mysql
      - mysql_config:/etc/mysql
volumes:
  mysql:
    driver: azure_file
    driver_opts:
      share_name: myfileshare
      storage_account_name: f29dsmysql

  mysql_config:
    driver: azure_file
    driver_opts: 
      share_name: myfileshareconfig
      storage_account_name: f29dsmysqlconfig